<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'home'                   => 'Pagrindinis',
    'budgets'                => 'Biudžetai',
    'subscriptions'          => 'Prenumeratos',
    'transactions'           => 'Pervedimai',
    'title_expenses'         => 'Išlaidos',
    'title_withdrawal'       => 'Išlaidos',
    'title_revenue'          => 'Pajamos / pajamos',
    'title_deposit'          => 'Pajamos / pajamos',
    'title_transfer'         => 'Pervedimai',
    'title_transfers'        => 'Pervedimai',
    'edit_currency'          => 'Redaguoti valiutą ":name"',
    'delete_currency'        => 'Redaguoti valiutą ":name"',
    'newPiggyBank'           => 'Sukurti naują taupyklę',
    'edit_piggyBank'         => 'Redaguoti taupyklę ":name"',
    'preferences'            => 'Nustatymai',
    'profile'                => 'Profilis',
    'accounts'               => 'Paskyros',
    'changePassword'         => 'Keisti slaptažodį',
    'change_email'           => 'Keisti el. pašto adresą',
    'bills'                  => 'Sąskaitos apmokėjimui',
    'newBill'                => 'Nauja sąskaita mokėjimui',
    'edit_bill'              => 'Redaguoti mokėjimo sąskaitą ":name"',
    'delete_bill'            => 'Trinti mokėjimo sąskaitą ":name"',
    'reports'                => 'Ataskaitos',
    'search_result'          => 'Paieškos rezultatai: ":query"',
    'withdrawal_list'        => 'Išlaidos',
    'Withdrawal_list'        => 'Išlaidos',
    'deposit_list'           => 'Pajamos ir indėliai',
    'transfer_list'          => 'Pavedimai',
    'transfers_list'         => 'Pavedimai',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'reconciliation_list'    => 'Patikra',
    'create_withdrawal'      => 'Sukurti naują išmoką',
    'create_deposit'         => 'Kurti naują įmoką',
    'create_transfer'        => 'Kurti naują pavedimą',
    'create_new_transaction' => 'Sukurkite naują operaciją',
    'edit_journal'           => 'Redaguoti operaciją ":description"',
    'edit_reconciliation'    => 'Redaguoti ":description"',
    'delete_journal'         => 'Ištrinti operaciją ":description"',
    'delete_group'           => 'Ištrinti operaciją ":description"',
    'tags'                   => 'Žymos',
    'createTag'              => 'Kurti naują žymą',
    'edit_tag'               => 'Redaguoti ":tag" žymą',
    'delete_tag'             => 'Šalinti ":tag" žymą',
    'delete_journal_link'    => 'Ištrinti nuoroda tarp operacijų',
    'edit_object_group'      => 'Redaguoti ":title" grupę',
    'delete_object_group'    => 'Trinti ":title" grupę',
    'logout_others'          => 'Atungti kitas sesijas',
    'asset_accounts'         => 'Turto sąskaitos',
    'expense_accounts'       => 'Išlaidų sąskaitos',
    'revenue_accounts'       => 'Pajamų sąskaitos',
    'liabilities_accounts'   => 'Finansiniai isipareigojimai',
    'placeholder'            => '[Paskirtoji vieta]',
];
