<?php

/**
 * firefly.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    '404_header'              => 'Firefly III negali rasti šio puslapio.',
    '404_page_does_not_exist' => 'Puslapis, kurio prašėte, neegzistuoja. Patikrinkite, ar neįvedėte neteisingo URL. Gal padarei rašybos klaidą?',
    '404_send_error'          => 'Jei buvote automatiškai nukreipti į šį puslapį, atsiprašau. Ši klaida minima jūsų žurnalo failuose ir būčiau dėkingas, jei atsiųstumėte man klaidą.',
    '404_github_link'         => 'Jei esate tikri, kad šis puslapis turėtų egzistuoti, atidarykite užklausa <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">GitHub</a></strong>.',
    'whoops'                  => 'Oi',
    'fatal_error'             => 'Įvyko lemtinga klaida. Patikrinkite žurnalo failus skiltyje „storage/logs“ arba naudokite „docker logs -f [container]“, kad pamatytumėte, kas vyksta.',
    'maintenance_mode'        => 'Firefly III veikia priežiūros režimu.',
    'be_right_back'           => 'Tuoj grįšiu!',
    'check_back'              => 'Firefly III is down for some necessary maintenance. Please check back in a second. If you happen to see this message on the demo site, just wait a few minutes. The database is reset every few hours.',
    'error_occurred'          => 'Oi! Įvyko klaida.',
    'db_error_occurred'       => 'Oi! Įvyko duomenų bazės klaida.',
    'error_not_recoverable'   => 'Deja, ši klaida nebuvo ištaisyta :(. Firefly III sugedo. Klaida yra:',
    'error'                   => 'Klaida',
    'error_location'          => 'Ši klaida įvyko faile <span style="font-family: monospace;">:file</span> eilutėje :line su kodu :code.',
    'stacktrace'              => 'Įrašas',
    'more_info'               => 'Daugiau informacijos',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'collect_info'            => 'Please collect more information in the <code>storage/logs</code> directory where you will find log files. If you\'re running Docker, use <code>docker logs -f [container]</code>.',
    'collect_info_more'       => 'Daugiau apie klaidų informacijos rinkimą galite perskaityti <a href="https://docs.firefly-iii.org/how-to/general/debug/">DUK</a>.',
    'github_help'             => 'Gaukite pagalbos „GitHub“',
    'github_instructions'     => 'Maloniai kviečiame atidaryti naują svarstoma problemą <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">„GitHub“</a></strong>.',
    'use_search'              => 'Pasinaudokite paieška!',
    'include_info'            => 'Įtraukite informaciją <a href=":link">iš šio derinimo puslapio</a>.',
    'tell_more'               => 'Pasakykite mums daugiau, nei sakoma "Oho!"',
    'include_logs'            => 'Įtraukite klaidų žurnalus (žr. aukščiau).',
    'what_did_you_do'         => 'Papasakokite, ką darėte.',
    'offline_header'          => 'Tikriausiai esate neprisijungęs',
    'offline_unreachable'     => 'Firefly III nepasiekiamas. Jūsų įrenginys šiuo metu neprisijungęs arba serveris neveikia.',
    'offline_github'          => 'Jei esate tikri, kad jūsų įrenginys ir serveris yra prijungti, atidarykite uzklausą <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">GitHub</a> </strong>.',
];
