<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'no_demo_text'           => 'Lo sentimos, no hay un texto de demostración extra para <abbr title=":route">esta página</abbr>.',
    'see_help_icon'          => 'Sin embargo, el icono <i class="fa fa-question-circle"></i>en la esquina superior derecha puede decirte más.',
    'index'                  => '¡Bienvenido a <strong>Firefly III</strong>! En esta página obtendrás un rápido resumen de tus finanzas. Para más información, échale un vistazo a las cuentas &rarr; <a href=":asset">cuentas de activos</a> y por supuesto las páginas <a href=":budgets">presupuestos</a> y <a href=":reports">informes</a>. O simplemente eche un vistazo a su alrededor y vea dónde termina.',
    'accounts-index'         => 'Las cuentas de activos son sus cuentas de banco personales. Las cuentas de gastos contienen sus gastos habituales como compras y salidas con amigos. Las cuentas de ingresos representan dinero que recibe de su trabajo, el gobierno u otras fuentes de ingresos. En esta página puede editarlas o eliminarlas.',
    'budgets-index'          => 'Esta página le muestra una visión general de sus presupuestos. La barra superior muestra la cantidad disponible para ser presupuestada. Esto se puede personalizar para cualquier período haciendo clic en la cantidad a la derecha. La cantidad que realmente has gastado se muestra en la barra de abajo. Debajo están los gastos por presupuesto y lo que has presupuestado para ellos.',
    'reports-index-start'    => 'Firefly III soporta varios tipos de informes. Lee sobre ellos haciendo clic en el icono <i class="fa fa-question-circle"></i>en la esquina superior derecha.',
    'reports-index-examples' => 'Asegúrese de revisar estos ejemplos: <a href=":one">un resumen financiero mensual</a>, <a href=":two">un resumen financiero anual</a> y <a href=":three">una visión general del presupuesto</a>.',
    'currencies-index'       => 'Firefly III soporta múltiples monedas. Aunque el euro es predeterminado se puede ajustar al Dólar de los Estados Unidos y a muchas otras monedas. Como puede ver una pequeña selección de monedas ha sido incluida, pero puede añadir la suya si lo desea. Sin embargo, cambiar la moneda por defecto no cambiará la moneda de las transacciones existentes: Firefly III soporta el uso de múltiples monedas al mismo tiempo.',
    'transactions-index'     => 'Estos gastos, depósitos y transferencias no son especialmente imaginativos, sino que se han generado automáticamente.',
    'piggy-banks-index'      => 'Como puedes ver, hay tres alcancías. Usa los botones "+" y "menos" para influir en la cantidad de dinero en cada alcancía. Haga clic en el nombre de la alcancía para ver la administración de cada alcancías.',
    'profile-index'          => 'Tenga en cuenta que el sitio de demostración se reinicia cada cuatro horas. Su acceso puede ser revocado en cualquier momento. Esto sucede automáticamente y no es un error.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
