<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'home'                   => 'ראשי',
    'budgets'                => 'תקציבים',
    'subscriptions'          => 'מנויים',
    'transactions'           => 'תנועות',
    'title_expenses'         => 'הוצאות',
    'title_withdrawal'       => 'הוצאות',
    'title_revenue'          => 'רווחים / הכנסות',
    'title_deposit'          => 'רווחים / הכנסות',
    'title_transfer'         => 'העברות',
    'title_transfers'        => 'העברות',
    'edit_currency'          => 'שנה מטבע: ":name"',
    'delete_currency'        => 'מחק מטבע ":name"',
    'newPiggyBank'           => 'צור קופת חיסכון חדשה',
    'edit_piggyBank'         => 'ערוך קופת חיסכון ":name"',
    'preferences'            => 'העדפות',
    'profile'                => 'פרופיל',
    'accounts'               => 'חשבונות',
    'changePassword'         => 'שנה את הסיסמה',
    'change_email'           => 'שנה כתובת מייל',
    'bills'                  => 'תשלומים',
    'newBill'                => 'תשלום חדש',
    'edit_bill'              => 'ערוך תשלום ":name"',
    'delete_bill'            => 'מחק תשלום ":name"',
    'reports'                => 'דוחות',
    'search_result'          => 'חפש תוצאות עבור ":query"',
    'withdrawal_list'        => 'הוצאות',
    'Withdrawal_list'        => 'הוצאות',
    'deposit_list'           => 'רווח, הכנסות וחסכונות',
    'transfer_list'          => 'העברות',
    'transfers_list'         => 'העברות',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'reconciliation_list'    => 'התאמת חשבונות',
    'create_withdrawal'      => 'צור משיכה חדשה',
    'create_deposit'         => 'צור הפקדה חדשה',
    'create_transfer'        => 'צור העברה חדשה',
    'create_new_transaction' => 'צור תנועה חדשה',
    'edit_journal'           => 'ערוך תנועה ":description"',
    'edit_reconciliation'    => 'ערוך ":description"',
    'delete_journal'         => 'מחק תנועה ":description"',
    'delete_group'           => 'מחק תנועה ":description"',
    'tags'                   => 'תגיות',
    'createTag'              => 'צור תגית חדשה',
    'edit_tag'               => 'עריכת תגית ":tag"',
    'delete_tag'             => 'מחיקת תגית ":tag"',
    'delete_journal_link'    => 'מחיקת קישור בין תנועות',
    'edit_object_group'      => 'עריכת קבוצה ":title"',
    'delete_object_group'    => 'מחיקת קבוצה ":title"',
    'logout_others'          => 'ניתוק כל הפעולות האחרות',
    'asset_accounts'         => 'חשבון נכסים',
    'expense_accounts'       => 'חשבונות הוצאות',
    'revenue_accounts'       => 'חשבונות הכנסות',
    'liabilities_accounts'   => 'התחייבויות',
    'placeholder'            => 'מציין מקום',

    // mfa
    'profile_mfa'            => 'Multi-factor authentication',
    'mfa_enableMFA'          => 'Enable multi-factor authentication',
    'mfa_backup_codes'       => 'Backup codes',
    'mfa_disableMFA'         => 'Disable multi-factor authentication',
];
