<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'no_demo_text'           => 'סליחה, אך לא נשאר הסבר הדגמה עבור <abbr title=":route"> עמוד הזה</abbr>.',
    'see_help_icon'          => 'אבל, התמונה <i class="fa fa-question-circle"> </i>בפינה ימנית עליונה מסוגלת לתת לך יותר מידע.',
    'index'                  => 'ברוכים הבאים ל<strong>Firefly III</strong>! כאן תוכלו לקבל מבט על מצב כלכלי שלך. למידע נוסף, בדוק &rarr;<a href=":asset">חשבון נכס</a> כמו גם עמודים של <a href=":budgets">תקציב</a> ו<a href=":reports">דוחות</a>. או באפשרותך להסתכל מסביב ולראות בעצמך לאיפה תגיע.',
    'accounts-index'         => 'חשבון נכסים הוא הבנק האישי של חשבון שלך. חשבון הוצאות הוא מקום לכל ההוצאות, כמו חברים, אוכל וחנויות. חשבון הכנסות חדש הוא הבית לכל ההכנסות, שם תרשום את כל המקומות מהם אתה מקבל כסף, כמו עבודה, תשלומים ממשלה, מתנות והכנסות אחרות. עמוד החוב הוא מקום לכל החובות והלוואות, כמו כרטיסי אשראי, הלוואות סטודנטים ומשכנתאות. בעמוד הזה תוכל לשנות אותם.',
    'budgets-index'          => 'This page shows you an overview of your budgets. The top bar shows the amount that is available to be budgeted. This can be customized for any period by clicking the amount on the right. The amount you\'ve actually spent is shown in the bar below. Below that are the expenses per budget and what you\'ve budgeted for them.',
    'reports-index-start'    => 'Firefly III supports a number of types of reports. Read about them by clicking on the <i class="fa fa-question-circle"></i>-icon in the top right corner.',
    'reports-index-examples' => 'Be sure to check out these examples: <a href=":one">a monthly financial overview</a>, <a href=":two">a yearly financial overview</a> and <a href=":three">a budget overview</a>.',
    'currencies-index'       => 'Firefly III supports multiple currencies. Although it defaults to the Euro it can be set to the US Dollar and many other currencies. As you can see a small selection of currencies has been included but you can add your own if you wish to. Changing the default currency will not change the currency of existing transactions however: Firefly III supports the use of multiple currencies at the same time.',
    'transactions-index'     => 'These expenses, deposits and transfers are not particularly imaginative. They have been generated automatically.',
    'piggy-banks-index'      => 'As you can see, there are three piggy banks. Use the plus and minus buttons to influence the amount of money in each piggy bank. Click the name of the piggy bank to see the administration for each piggy bank.',
    'profile-index'          => 'Keep in mind that the demo site resets every four hours. Your access may be revoked at any time. This happens automatically and is not a bug.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
