<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'home'                   => 'خانه',
    'budgets'                => 'بودجه بندی ها',
    'subscriptions'          => 'اشتراک ها',
    'transactions'           => 'تراکنش ها',
    'title_expenses'         => 'هزینه ها',
    'title_withdrawal'       => 'هزینه ها',
    'title_revenue'          => 'درآمد',
    'title_deposit'          => 'درآمد',
    'title_transfer'         => 'انتقال ها',
    'title_transfers'        => 'انتقال ها',
    'edit_currency'          => 'ویرایش واحد پولی ":name"',
    'delete_currency'        => 'حذف واحد پولی ":name"',
    'newPiggyBank'           => 'ایجاد یک قلک جدید',
    'edit_piggyBank'         => 'اصلاح نام قلک ":name"',
    'preferences'            => 'تنظیمات',
    'profile'                => 'حساب کاربری',
    'accounts'               => 'حساب ها',
    'changePassword'         => 'رمز عبور خود را تغییر دهید',
    'change_email'           => 'آدرس ایمیل خود را تغییر دهید',
    'bills'                  => 'قبوض',
    'newBill'                => 'صورتحساب جدید',
    'edit_bill'              => 'اصلاح قبض ":name"',
    'delete_bill'            => 'حذف قبض ":name"',
    'reports'                => 'گزارشات',
    'search_result'          => 'نتایج جستجو برای عبارت ":query"\'',
    'withdrawal_list'        => 'هزینه ها',
    'Withdrawal_list'        => 'هزینه ها',
    'deposit_list'           => 'درآمد، عایدات و سپرده ها',
    'transfer_list'          => 'انتقال ها',
    'transfers_list'         => 'انتقال ها',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'reconciliation_list'    => 'صورت مغایرات',
    'create_withdrawal'      => 'ایجاد خرج جدید',
    'create_deposit'         => 'ایجاد دخل جدید',
    'create_transfer'        => 'ایجاد انتقال جدید',
    'create_new_transaction' => 'ایجاد تراکنش جدید',
    'edit_journal'           => 'اصلاح تراکنش ":description"',
    'edit_reconciliation'    => 'اصلاح ":description"',
    'delete_journal'         => 'حذف تراکنش ":description"',
    'delete_group'           => 'حذف تراکنش ":description"',
    'tags'                   => 'برچسب ها',
    'createTag'              => 'ایجاد برچسب جدید',
    'edit_tag'               => 'اصلاح برچسب ":tag"',
    'delete_tag'             => 'حذف برچسب ":tag"',
    'delete_journal_link'    => 'حذف پیوند بین تراکنش ها',
    'edit_object_group'      => 'اصلاح گروه ":title"',
    'delete_object_group'    => 'حذف گروه ":title"',
    'logout_others'          => 'خروج از نشست‌های دیگر',
    'asset_accounts'         => 'حساب های دارایی',
    'expense_accounts'       => 'حساب های مخارج',
    'revenue_accounts'       => 'حساب های درآمد',
    'liabilities_accounts'   => 'بدهی ها',
    'placeholder'            => '[Placeholder]',
];
