<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'no_demo_text'           => 'متأسفیم، هیچ متن توضیحی اضافی برای <abbr title=":route">این صفحه< وجود ندارد',
    'see_help_icon'          => 'با این حال، نماد <i class="fa fa-question-circle"></i>-در گوشه سمت راست بالا ممکن است چیزهای بیشتری به شما بگوید.',
    'index'                  => 'به <strong>Firefly III</strong> خوش آمدید! در این صفحه یک نمای کلی از امور مالی خود دریافت می کنید. برای اطلاعات بیشتر، حساب‌ها را بررسی کنید &rarr; <a href=":asset">حساب‌های دارایی</a> و البته صفحات <a href=":budgets">بودجه‌ها</a> و <a href=":reports">گزارش‌ها</a>. یا فقط نگاهی به اطراف بیندازید و ببینید به کجا می رسید.',
    'accounts-index'         => 'حساب‌های دارایی، حساب‌های بانکی شخصی شما هستند. حساب‌های هزینه، حساب‌هایی هستند که در آنها پول خرج می‌کنید، مانند فروشگاه‌ها و دوستان. حساب‌های درآمد، حساب‌هایی هستند که از آنها پول دریافت می‌کنید، مانند شغل، دولت یا سایر منابع درآمد. بدهی ها بدهی ها و وام های شما مانند بدهی های قدیمی کارت اعتباری یا وام های دانشجویی هستند. در این صفحه می توانید آنها را ویرایش یا حذف کنید.
',
    'budgets-index'          => 'این صفحه یک نمای کلی از بودجه شما را به شما نشان می دهد. نوار بالایی مقداری را که برای بودجه بندی در دسترس است نشان می دهد. این را می توان برای هر دوره ای با کلیک کردن روی مقدار سمت راست سفارشی کرد. مبلغی که واقعاً خرج کرده اید در نوار زیر نشان داده شده است. در زیر آن هزینه های هر بودجه و آنچه که برای آنها در نظر گرفته اید آمده است.
',
    'reports-index-start'    => 'Firefly III از تعدادی از انواع گزارش ها پشتیبانی می کند. با کلیک بر روی نماد <i class="fa fa-question-circle"></i>-در گوشه سمت راست بالا، در مورد آنها مطالعه کنید.
',
    'reports-index-examples' => 'حتماً این نمونه‌ها را بررسی کنید: <a href=":one">نمای کلی مالی ماهانه</a>، <a href=":two">نمای کلی مالی سالانه</a> و <a href=": three">نمای کلی بودجه</a>.
',
    'currencies-index'       => 'Firefly III از چندین ارز پشتیبانی می کند. اگرچه پیش‌فرض آن یورو است، اما می‌توان آن را روی دلار آمریکا و بسیاری از ارزهای دیگر تنظیم کرد. همانطور که می بینید مجموعه کوچکی از ارزها گنجانده شده است، اما در صورت تمایل می توانید ارزهای خود را اضافه کنید. با این حال، تغییر واحد پول پیش‌فرض، واحد پول تراکنش‌های موجود را تغییر نمی‌دهد: Firefly III از استفاده همزمان از چندین ارز پشتیبانی می‌کند.
',
    'transactions-index'     => 'این مخارج، سپرده ها و نقل و انتقالات چندان تخیلی نیستند. آنها به طور خودکار تولید شده اند.
',
    'piggy-banks-index'      => 'همانطور که می بینید، سه قلک وجود دارد. از دکمه های مثبت و منفی برای تأثیرگذاری بر میزان پول در هر قلک استفاده کنید. برای مشاهده مدیریت هر قلک، روی نام قلک کلیک کنید.
',
    'profile-index'          => 'به خاطر داشته باشید که سایت دمو هر چهار ساعت یکبار بازنشانی می شود. دسترسی شما ممکن است در هر زمانی لغو شود. این به طور خودکار اتفاق می افتد و یک باگ نیست.
',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
