<?php

/**
 * intro.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    // index
    'index_intro'                                             => 'به صفحه فهرست فایرفلای III خوش آمدید. لطفاً برای قدم زدن در این مقدمه وقت بگذارید تا احساس کنید که Firefly III چگونه کار می کند.',
    'index_accounts-chart'                                    => 'این نمودار موجودی فعلی حساب های دارایی شما را نشان می دهد. می توانید حساب های قابل مشاهده در اینجا را در تنظیمات برگزیده خود انتخاب کنید.',
    'index_box_out_holder'                                    => 'این جعبه کوچک و جعبه های کنار این جعبه به شما یک نمای کلی از وضعیت مالی شما می دهد.',
    'index_help'                                              => 'اگر در مورد یک صفحه یا فرم نیاز به کمک داشتید، این دکمه را فشار دهید.',
    'index_outro'                                             => 'بیشتر صفحات Firefly III با تور کوچکی مانند این شروع می شود. لطفا در صورت داشتن سؤال یا نظر با من تماس بگیرید. لذت ببرید!',
    'index_sidebar-toggle'                                    => 'برای ایجاد تراکنش‌ها، حساب‌ها یا موارد دیگر، از منوی زیر این نماد استفاده کنید.',
    'index_cash_account'                                      => 'اینها اکانت هایی هستند که تاکنون ایجاد شده اند. شما می توانید از حساب نقدی برای پیگیری هزینه های نقدی استفاده کنید، اما البته اجباری نیست.',

    // transactions
    'transactions_create_basic_info'                          => 'اطلاعات اولیه تراکنش خود را وارد کنید. منبع، مقصد، تاریخ و توضیحات.',
    'transactions_create_amount_info'                         => 'مبلغ معامله را وارد کنید. در صورت لزوم، فیلدها برای اطلاعات مقدار خارجی به طور خودکار به روز می شوند.',
    'transactions_create_optional_info'                       => 'تمامی گزینه ها انتخابی هستند. افزودن متا داده در اینجا تراکنش های شما را بهتر سازماندهی می کند.',
    'transactions_create_split'                               => 'اگر می خواهید یک تراکنش را تقسیم کنید، با این دکمه تقسیم های بیشتری اضافه کنید',

    // create account:
    'accounts_create_iban'                                    => 'به حساب های خود یک IBAN معتبر بدهید. این می تواند واردات داده را در آینده بسیار آسان کند.',
    'accounts_create_asset_opening_balance'                   => 'حساب‌های دارایی‌ها ممکن است دارای «تراز اولیه» باشند که نشان‌دهنده شروع تاریخچه این حساب در Firefly III است.',
    'accounts_create_asset_currency'                          => 'Firefly III از چندین ارز پشتیبانی می کند. حساب‌های دارایی دارای یک ارز اصلی هستند که باید آن را در اینجا تنظیم کنید.',
    'accounts_create_asset_virtual'                           => 'گاهی اوقات می‌توان به حساب خود یک موجودی مجازی داد: مبلغ اضافی همیشه به موجودی واقعی اضافه یا از آن حذف می‌شود.',

    // budgets index
    'budgets_index_intro'                                     => 'بودجه برای مدیریت امور مالی شما و تشکیل یکی از عملکردهای اصلی Firefly III استفاده می شود.',
    'budgets_index_see_expenses_bar'                          => 'خرج کردن پول کم کم این نوار را پر می کند.',
    'budgets_index_navigate_periods'                          => 'در میان دوره‌ها پیمایش کنید تا به راحتی بودجه‌ها را زودتر از موعد تعیین کنید.',
    'budgets_index_new_budget'                                => 'بودجه های جدید را به دلخواه خود ایجاد کنید.',
    'budgets_index_list_of_budgets'                           => 'از این جدول برای تعیین مقادیر برای هر بودجه استفاده کنید و ببینید که چگونه کار می کنید.',
    'budgets_index_outro'                                     => 'برای کسب اطلاعات بیشتر درباره بودجه بندی، نماد راهنما را در گوشه سمت راست بالا بررسی کنید.',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    // reports (index)
    'reports_index_intro'                                     => 'از این گزارش ها برای دریافت اطلاعات دقیق در مورد امور مالی خود استفاده کنید.',
    'reports_index_inputReportType'                           => 'یک نوع گزارش را انتخاب کنید. صفحات راهنما را بررسی کنید تا ببینید هر گزارش چه چیزی را به شما نشان می دهد.',
    'reports_index_inputAccountsSelect'                       => 'می‌توانید حساب‌های دارایی را به دلخواه حذف یا اضافه کنید.',
    'reports_index_inputDateRange'                            => 'محدوده تاریخ انتخاب شده کاملاً به شما بستگی دارد: از یک روز تا 10 سال یا بیشتر.',
    'reports_index_extra-options-box'                         => 'بسته به گزارشی که انتخاب کرده اید، می توانید فیلترها و گزینه های اضافی را در اینجا انتخاب کنید. وقتی نوع گزارش را تغییر می‌دهید، این کادر را تماشا کنید.',

    // reports (reports)
    'reports_report_default_intro'                            => 'این گزارش یک نمای کلی سریع و جامع از امور مالی شما ارائه می دهد. اگر می خواهید چیز دیگری ببینید، لطفا دریغ نکنید با من تماس بگیرید!',
    'reports_report_audit_intro'                              => 'این گزارش به شما اطلاعات دقیقی از حساب‌های دارایی‌تان می‌دهد.',
    'reports_report_audit_optionsBox'                         => 'از این چک باکس ها برای نمایش یا پنهان کردن ستون های مورد علاقه خود استفاده کنید.',

    'reports_report_category_intro'                           => 'این گزارش به شما بینشی در یک یا چند دسته می دهد.',
    'reports_report_category_pieCharts'                       => 'این نمودارها بینشی در مورد هزینه ها و درآمد در هر دسته یا هر حساب به شما می دهد.',
    'reports_report_category_incomeAndExpensesChart'          => 'این نمودار هزینه ها و درآمد شما را در هر دسته نشان می دهد.',

    'reports_report_tag_intro'                                => 'این گزارش به شما بینشی در یک یا چند تگ می دهد.',
    'reports_report_tag_pieCharts'                            => 'این نمودارها بینشی در مورد هزینه ها و درآمد هر برچسب، حساب، دسته یا بودجه به شما می دهد.',
    'reports_report_tag_incomeAndExpensesChart'               => 'این نمودار هزینه ها و درآمد شما را به ازای هر برچسب نشان می دهد.',

    'reports_report_budget_intro'                             => 'این گزارش به شما بینشی در مورد یک یا چند بودجه می دهد.',
    'reports_report_budget_pieCharts'                         => 'این نمودارها به شما بینشی در مورد هزینه های هر بودجه یا هر حساب می دهد.',
    'reports_report_budget_incomeAndExpensesChart'            => 'این نمودار هزینه های هر بودجه شما را نشان می دهد.',

    // create transaction
    'transactions_create_switch_box'                          => 'از این دکمه ها برای تغییر سریع نوع تراکنشی که می خواهید ذخیره کنید استفاده کنید.',
    'transactions_create_ffInput_category'                    => 'می توانید آزادانه در این قسمت تایپ کنید. دسته‌هایی که قبلا ایجاد شده‌اند پیشنهاد خواهند شد.',
    'transactions_create_withdrawal_ffInput_budget'           => 'برای کنترل مالی بهتر، برداشت خود را به بودجه مرتبط کنید.',
    'transactions_create_withdrawal_currency_dropdown_amount' => 'زمانی که برداشت شما به ارز دیگری است از این منوی کشویی استفاده کنید.',
    'transactions_create_deposit_currency_dropdown_amount'    => 'زمانی که سپرده شما به ارز دیگری است از این منوی کشویی استفاده کنید.',
    'transactions_create_transfer_ffInput_piggy_bank_id'      => 'یک قلک را انتخاب کنید و این انتقال را به پس انداز خود پیوند دهید.',

    // piggy banks index:
    'piggy-banks_index_saved'                                 => 'این قسمت به شما نشان می دهد که در هر قلک چقدر پس انداز کرده اید.',
    'piggy-banks_index_button'                                => 'در کنار این نوار پیشرفت دو دکمه (+ و -) برای اضافه کردن یا حذف پول از هر قلک وجود دارد.',
    'piggy-banks_index_accountStatus'                         => 'برای هر حساب دارایی با حداقل یک قلک وضعیت در این جدول ذکر شده است.',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    // create piggy
    'piggy-banks_create_name'                                 => 'هدف شما چیست؟ کاناپه جدید، دوربین، پول برای مواقع اضطراری؟',
    'piggy-banks_create_date'                                 => 'شما می توانید یک تاریخ هدف یا یک ضرب الاجل برای قلک خود تعیین کنید.',

    // show piggy
    'piggy-banks_show_piggyChart'                             => 'این نمودار تاریخچه این قلک را نشان می دهد.',
    'piggy-banks_show_piggyDetails'                           => 'برخی از جزئیات در مورد قلک شما',
    'piggy-banks_show_piggyEvents'                            => 'هر گونه اضافه یا حذف نیز در اینجا فهرست شده است.',

    // bill index
    'bills_index_rules'                                       => 'در اینجا می بینید که کدام قوانین بررسی می کنند که آیا این لایحه مورد بررسی قرار می گیرد',
    'bills_index_paid_in_period'                              => 'این فیلد آخرین زمان پرداخت صورت حساب را نشان می دهد.',
    'bills_index_expected_in_period'                          => 'این فیلد برای هر صورتحساب نشان می‌دهد که آیا و چه زمانی صورت‌حساب بعدی مورد انتظار است.',

    // show bill
    'bills_show_billInfo'                                     => 'این جدول اطلاعات کلی در مورد این لایحه را نشان می دهد.',
    'bills_show_billButtons'                                  => 'از این دکمه برای اسکن مجدد تراکنش های قدیمی استفاده کنید تا با این صورتحساب مطابقت داشته باشند.',
    'bills_show_billChart'                                    => 'این نمودار تراکنش های مرتبط با این صورت حساب را نشان می دهد.',

    // create bill
    'bills_create_intro'                                      => 'از صورتحساب ها برای ردیابی مقدار پولی که در هر دوره باید پرداخت می کنید استفاده کنید. به هزینه هایی مانند اجاره، بیمه یا پرداخت وام مسکن فکر کنید.',
    'bills_create_name'                                       => 'از یک نام توصیفی مانند «اجاره» یا «بیمه سلامت» استفاده کنید.',
    // 'bills_create_match'                                      => 'To match transactions, use terms from those transactions or the expense account involved. All words must match.',
    'bills_create_amount_min_holder'                          => 'حداقل و حداکثر مبلغ را برای این صورتحساب انتخاب کنید.',
    'bills_create_repeat_freq_holder'                         => 'اکثر صورت‌حساب‌ها ماهانه تکرار می‌شوند، اما می‌توانید فرکانس دیگری را در اینجا تنظیم کنید.',
    'bills_create_skip_holder'                                => 'اگر یک صورتحساب هر 2 هفته تکرار شود، قسمت "پرش" باید روی "1" تنظیم شود تا یک هفته در میان رد شود.',

    // rules index
    'rules_index_intro'                                       => 'Firefly III به شما امکان می دهد قوانینی را مدیریت کنید که به طور خودکار برای هر تراکنشی که ایجاد یا ویرایش می کنید اعمال می شود.
',
    'rules_index_new_rule_group'                              => 'شما می توانید قوانین را در گروه ها برای مدیریت آسان تر ترکیب کنید.',
    'rules_index_new_rule'                                    => 'هر تعداد که دوست دارید قوانین ایجاد کنید.',
    'rules_index_prio_buttons'                                => 'آنها را هر طور که صلاح می دانید سفارش دهید.',
    'rules_index_test_buttons'                                => 'می توانید قوانین خود را آزمایش کنید یا آنها را در تراکنش های موجود اعمال کنید.',
    'rules_index_rule-triggers'                               => 'قوانین دارای «محرک‌ها» و «عمل‌هایی» هستند که می‌توانید آنها را با کشیدن و رها کردن سفارش دهید.',
    'rules_index_outro'                                       => 'حتماً صفحات راهنما را با استفاده از نماد (؟) در بالا سمت راست بررسی کنید!',

    // create rule:
    'rules_create_mandatory'                                  => 'یک عنوان توصیفی را انتخاب کنید و تعیین کنید که قانون باید چه زمانی اجرا شود.',
    'rules_create_ruletriggerholder'                          => 'هر تعداد ماشه را که دوست دارید اضافه کنید، اما به یاد داشته باشید که همه محرک ها باید قبل از انجام هر اقدامی مطابقت داشته باشند.',
    'rules_create_test_rule_triggers'                         => 'از این دکمه استفاده کنید تا ببینید کدام تراکنش ها با قانون شما مطابقت دارند.',
    'rules_create_actions'                                    => 'هر تعداد عمل را که دوست دارید تنظیم کنید.',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    // preferences
    'preferences_index_tabs'                                  => 'گزینه های بیشتری در پشت این برگه ها موجود است.',

    // currencies
    'currencies_index_intro'                                  => 'Firefly III از چندین ارز پشتیبانی می کند که می توانید آنها را در این صفحه تغییر دهید.',
    'currencies_index_default'                                => 'Firefly III یک ارز پیش فرض دارد.',
    'currencies_index_buttons'                                => 'از این دکمه ها برای تغییر واحد پول پیش فرض یا فعال کردن سایر ارزها استفاده کنید.',

    // create currency
    'currencies_create_code'                                  => 'این کد باید مطابق با ISO باشد (آن را برای ارز جدید خود در گوگل جستجو کنید).',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
