<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'buttons'                 => 'دکمه‌ها',
    'icon'                    => 'نماد',
    'id'                      => 'شناسه',
    'create_date'             => 'ایجاد شده در',
    'update_date'             => 'به روز شده در',
    'updated_at'              => 'به روز شده در',
    'balance_before'          => 'موجودی قبل',
    'balance_after'           => 'موجودی بعد',
    'name'                    => 'نام',
    'role'                    => 'نقش',
    'currentBalance'          => 'موجودی فعلی: ',
    'linked_to_rules'         => 'قوانین مرتبط',
    'active'                  => 'فعال است؟',
    'percentage'              => 'درصد',
    'recurring_transaction'   => 'معامله مکرر
',
    'next_due'                => 'دوره بعدی',
    'transaction_type'        => 'نوع',
    'lastActivity'            => 'آخرین فعالیت',
    'balanceDiff'             => 'تفاوت موجودی





',
    'other_meta_data'         => 'سایر متا داده‌ها





',
    'invited_at'              => 'دعوت‌شده در





',
    'expires'                 => 'دعوتنامه منقضی می شود
',
    'invited_by'              => 'دعوت شده توسط
',
    'invite_link'             => 'لینک دعوت
',
    'account_type'            => 'نوع حساب
',
    'created_at'              => 'ایجاد شده در
',
    'account'                 => 'حساب',
    'external_url'            => 'آدرس وب سایت خروجی',
    'matchingAmount'          => 'مبلغ',
    'destination'             => 'مقصد',
    'source'                  => 'منبع',
    'next_expected_match'     => 'مسابقه بعدی مورد انتظار
',
    'automatch'               => 'همسان سازی خودکار',
    'drag_and_drop'           => 'Drag and drop',
    'number'                  => 'Account number',
    'current_balance'         => 'Current balance',
    'last_activity'           => 'Last activity',
    'amount_due'              => 'Amount due',
    'balance_difference'      => 'Balance difference',
    'menu'                    => 'Menu',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'repeat_freq'             => 'تکرار‌ها',
    'description'             => 'توضیحات',
    'amount'                  => 'مبلغ',
    'date'                    => 'تاریخ',
    'interest_date'           => 'تاریخ بهره
',
    'book_date'               => 'تاریخ کتاب',
    'process_date'            => 'تاریخ پردازش',
    'due_date'                => 'تاریخ سررسید',
    'payment_date'            => 'تاریخ پرداخت',
    'invoice_date'            => 'تاریخ فاکتور',
    'internal_reference'      => 'مرجع داخلی
',
    'notes'                   => 'یادداشت‌ها',
    'from'                    => 'از نوع',
    'piggy_bank'              => 'صندوق پس‌انداز





',
    'to'                      => 'به',
    'budget'                  => 'بودجه',
    'category'                => 'دسته بندی',
    'bill'                    => 'صورت حساب',
    'withdrawal'              => 'درخواست برداشت',
    'deposit'                 => 'سپرده',
    'transfer'                => 'انتقال',
    'type'                    => 'نوع',
    'completed'               => 'تکمیل شده',
    'iban'                    => 'شماره حساب بین‌المللی (IBAN)





',
    'account_number'          => 'شماره حساب',
    'paid_current_period'     => 'در این دوره پرداخت شده





',
    'email'                   => 'ایمیل',
    'registered_at'           => 'ثبت شده در





',
    'is_blocked'              => 'مسدود شده است',
    'is_admin'                => 'ادمین است؟
',
    'has_two_factor'          => 'دو عاملی است





',
    'blocked_code'            => 'کد بلوک





',
    'source_account'          => 'حساب اصلی
',
    'destination_account'     => 'حساب مقصد
',
    'accounts_count'          => 'تعداد حساب‌ها





',
    'journals_count'          => 'تعداد تراکنش‌ها:',
    'attachments_count'       => 'تعداد پیوست ها',
    'bills_count'             => 'تعداد قبوض
',
    'categories_count'        => 'تعداد دسته ها
',
    'budget_count'            => 'تعداد بودجه
',
    'rule_and_groups_count'   => 'تعداد قوانین و گروه های قوانین
',
    'tags_count'              => 'تعداد تگ ها
',
    'tags'                    => 'برچسب ها',
    'inward'                  => 'توضیحات ورودی





',
    'outward'                 => 'توضیحات خروجی





',
    'number_of_transactions'  => 'تعداد تراکنش‌ها





',
    'total_amount'            => 'مبلغ کل',
    'sum'                     => 'مجموع',
    'sum_excluding_transfers' => 'جمع (بدون انتقال)





',
    'sum_withdrawals'         => 'مجموع برداشت‌ها





',
    'sum_deposits'            => 'مجموع سپرده ها
',
    'sum_transfers'           => 'مجموع نقل و انتقالات
',
    'sum_reconciliations'     => 'جمع تطابق‌ها





',
    'reconcile'               => 'تطابق





',
    'sepa_ct_id'              => 'شناسه پایان به پایان SEPA





',
    'sepa_ct_op'              => 'شناسه حساب مخالف SEPA





',
    'sepa_db'                 => 'شناسه مأموریت SEPA
',
    'sepa_country'            => 'کشور SEPA





',
    'sepa_cc'                 => 'کد پاک‌سازی SEPA





',
    'sepa_ep'                 => 'هدف خارجی SEPA





',
    'sepa_ci'                 => 'شناسه اعتباردهنده SEPA





',
    'sepa_batch_id'           => 'شناسه دسته SEPA





',
    'external_id'             => 'شناسه خارجی
',
    'account_at_bunq'         => 'حساب با bunq





',
    'file_name'               => 'نام فایل',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'file_size'               => 'سایز فایل',
    'file_type'               => 'نوع فايل',
    'attached_to'             => 'ضمیمه شده به',
    'file_exists'             => 'فایل وجود دارد',
    'spectre_bank'            => 'بانک',
    'spectre_last_use'        => 'آخرین ورود',
    'spectre_status'          => 'وضعیت',
    'bunq_payment_id'         => 'شناسه پرداخت bunq
',
    'repetitions'             => 'تکرارها',
    'title'                   => 'عنوان',
    'transaction_s'           => 'تراکنش‌ها',
    'field'                   => 'فیلد',
    'value'                   => 'مقدار',
    'interest'                => 'سود',
    'interest_period'         => 'سود دوره ای',
    'liability_type'          => 'نوع مسئولیت
',
    'liability_direction'     => 'مسئولیت در / خارج
',
    'end_date'                => 'تاریخ پایان',
    'payment_info'            => 'اطلاعات پرداخت',
    'expected_info'           => 'معامله مورد انتظار بعدی
',
    'start_date'              => 'تاریخ شروع',
    'trigger'                 => 'راه‌انداز',
    'response'                => 'پاسخ',
    'delivery'                => 'تحویل',
    'url'                     => 'نشانی ‌URL',
    'secret'                  => 'محرمانه',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
