<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'home'                   => 'Početak',
    'budgets'                => 'Budžet',
    'subscriptions'          => 'Pretplate',
    'transactions'           => 'Transakcije',
    'title_expenses'         => 'Troškovi',
    'title_withdrawal'       => 'Troškovi',
    'title_revenue'          => 'Revenue / income',
    'title_deposit'          => 'Revenue / income',
    'title_transfer'         => 'Prenosi',
    'title_transfers'        => 'Transfers',
    'edit_currency'          => 'Izmenite detalje o valuti ":name"',
    'delete_currency'        => 'Izbrišite valutu ":name"',
    'newPiggyBank'           => 'Otvorite novu "kasicu-prasicu"',
    'edit_piggyBank'         => 'Izmenite kasicu-prasicu ":name"',
    'preferences'            => 'Podešavanja',
    'profile'                => 'Profil',
    'accounts'               => 'Accounts',
    'changePassword'         => 'Promenite lozinku',
    'change_email'           => 'Promenite e-mail adresu',
    'bills'                  => 'Računi',
    'newBill'                => 'New bill',
    'edit_bill'              => 'Edit bill ":name"',
    'delete_bill'            => 'Delete bill ":name"',
    'reports'                => 'Izveštaji',
    'search_result'          => 'Search results for ":query"',
    'withdrawal_list'        => 'Troškovi',
    'Withdrawal_list'        => 'Troškovi',
    'deposit_list'           => 'Revenue, income and deposits',
    'transfer_list'          => 'Transfers',
    'transfers_list'         => 'Transfers',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'reconciliation_list'    => 'Reconciliations',
    'create_withdrawal'      => 'Create new withdrawal',
    'create_deposit'         => 'Create new deposit',
    'create_transfer'        => 'Create new transfer',
    'create_new_transaction' => 'Kreiraj transakciju',
    'edit_journal'           => 'Edit transaction ":description"',
    'edit_reconciliation'    => 'Edit ":description"',
    'delete_journal'         => 'Delete transaction ":description"',
    'delete_group'           => 'Delete transaction ":description"',
    'tags'                   => 'Tags',
    'createTag'              => 'Create new tag',
    'edit_tag'               => 'Edit tag ":tag"',
    'delete_tag'             => 'Delete tag ":tag"',
    'delete_journal_link'    => 'Delete link between transactions',
    'edit_object_group'      => 'Edit group ":title"',
    'delete_object_group'    => 'Delete group ":title"',
    'logout_others'          => 'Logout other sessions',
    'asset_accounts'         => 'Asset accounts',
    'expense_accounts'       => 'Expense accounts',
    'revenue_accounts'       => 'Revenue accounts',
    'liabilities_accounts'   => 'Liabilities',
    'placeholder'            => '[Placeholder]',
];
