<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'home'                   => 'Početak',
    'budgets'                => 'Budžet',
    'subscriptions'          => 'Pretplate',
    'transactions'           => 'Transakcije',
    'title_expenses'         => 'Troškovi',
    'title_withdrawal'       => 'Troškovi',
    'title_revenue'          => 'Zarada / prihod',
    'title_deposit'          => 'Zarada / prihod',
    'title_transfer'         => 'Prenosi',
    'title_transfers'        => 'Transferi',
    'edit_currency'          => 'Izmenite detalje o valuti ":name"',
    'delete_currency'        => 'Izbrišite valutu ":name"',
    'newPiggyBank'           => 'Otvorite novu "kasicu-prasicu"',
    'edit_piggyBank'         => 'Izmenite kasicu-prasicu ":name"',
    'preferences'            => 'Podešavanja',
    'profile'                => 'Profil',
    'accounts'               => 'Računi',
    'changePassword'         => 'Promenite lozinku',
    'change_email'           => 'Promenite e-mail adresu',
    'bills'                  => 'Računi',
    'newBill'                => 'Novi račun',
    'edit_bill'              => 'Izmijenite račun ":name"',
    'delete_bill'            => 'Izbrišite račun ":name"',
    'reports'                => 'Izvještaji',
    'search_result'          => 'Rezultati pretrage za ":query"',
    'withdrawal_list'        => 'Troškovi',
    'Withdrawal_list'        => 'Troškovi',
    'deposit_list'           => 'Zarada, prihod i depozit',
    'transfer_list'          => 'Transferi',
    'transfers_list'         => 'Transferi',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'reconciliation_list'    => '',
    'create_withdrawal'      => 'Kreirajte novu isplatu',
    'create_deposit'         => 'Kreirajte novu uplatu',
    'create_transfer'        => 'Kreirajte novi transfer',
    'create_new_transaction' => 'Kreiraj transakciju',
    'edit_journal'           => 'Izmijenite transakciju ":description"',
    'edit_reconciliation'    => 'Izmijenite ":description"',
    'delete_journal'         => 'Izbrišite transakciju ":description"',
    'delete_group'           => 'Izbrišite transakciju ":description"',
    'tags'                   => 'Tagovi',
    'createTag'              => 'Kreirajte novi tag',
    'edit_tag'               => 'Izmijenite tag ":tag"',
    'delete_tag'             => 'Izbrišite tag ":tag"',
    'delete_journal_link'    => 'Ukolnite vezu između transakcija',
    'edit_object_group'      => 'Izmijenite grupu ":title"',
    'delete_object_group'    => 'Izbrišite grupu ":title"',
    'logout_others'          => 'Izlogujte se iz ostalih sesija',
    'asset_accounts'         => 'Računi imovine',
    'expense_accounts'       => 'Računi troškova',
    'revenue_accounts'       => 'Računi prihoda',
    'liabilities_accounts'   => 'Obaveze',
    'placeholder'            => '[Placeholder]',

    // mfa
    'profile_mfa'            => 'Višefaktorska autentifikacija',
    'mfa_enableMFA'          => 'Uključite višefaktorsku autentifikaciju',
    'mfa_backup_codes'       => 'Rezervni kodovi',
    'mfa_disableMFA'         => 'Isključite višefaktorsku autentifikaciju',
];
