<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'no_demo_text'           => 'Žao nam je, ne postoji dodatni tekst demo-objašnjenja za <abbr title=":route">ovu stranicu</abbr>.',
    'see_help_icon'          => 'Međutim, ikonica <i class="fa fa-question-circle"></i>-u gornjem desnom uglu može vam reći više.',
    'index'                  => 'Dobrodošli u <strong>Firefly III</strong>! Na ovoj stranici dobijate brzi pregled vaših finansija. Za više informacija pogledajte Računi &rarr; <a href=":asset">Računi sredstava</a> i naravno stranice <a href=":budgets">Budžeti</a> i <a href=":reports">Izvještaji</a>. Ili samo pogledajte okolo i vidite gdje ćete završiti.',
    'accounts-index'         => "Računi sredstava su vaši lični bankovni računi. Računi troškova su računi na koje trošite novac, kao što su trgovine i prijatelji. Računi prihoda su računi sa kojih primate novac, kao što su vaš posao, vlada ili drugi izvori prihoda. Obaveze su vaši dugovi i zajmovi poput starih dugova po kreditnoj kartici ili studentskih kredita. Na ovoj stranici ih možete uređivati \u{200b}\u{200b}ili uklanjati.",
    'budgets-index'          => 'Ova stranica vam prikazuje pregled vaših budžeta. Gornja traka prikazuje iznos koji je dostupan za budžet. Ovo se može prilagoditi za bilo koji period klikom na iznos s desne strane. Iznos koji ste stvarno potrošili prikazan je u traci ispod. Ispod toga su troškovi po budžetu i ono što ste planirali za njih.',
    'reports-index-start'    => 'Firefly III podržava brojne tipove izvještaja. Pročitajte o njima klikom na <i class="fa fa-question-circle"></i>-ikonicu u gornjem desnom uglu.',
    'reports-index-examples' => 'Obavezno pogledajte ove primjere: <a href=":one">mjesečni finansijski pregled</a>, <a href=":two">godišnji finansijski pregled</a> i
<a href=":three">pregled budžeta</a>.',
    'currencies-index'       => 'FireflyFirefly III podržava više valuta. Iako je zadana vrijednost eura, može se postaviti na američki dolar i mnoge druge valute. Kao što vidite mali izbor valuta je uključen, ali možete dodati svoju ako želite. Međutim, promjena zadane valute neće promijeniti valutu postojećih transakcija: Firefly III podržava korištenje više valuta u isto vrijeme.',
    'transactions-index'     => 'Ovi troškovi, depoziti i transferi nisu posebno maštoviti. Generisani su automatski.',
    'piggy-banks-index'      => 'Kao što vidite, postoje tri kasice. Koristite dugmad plus i minus da utičete na količinu novca u svakoj kasici prasici. Kliknite na naziv kasice prasice da vidite administraciju za svaku kasicu prasicu.',
    'profile-index'          => 'Imajte na umu da se demo stranica resetuje svaka četiri sata. Vaš pristup može biti opozvan u bilo kojem trenutku. Ovo se dešava automatski i nije greška.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
