<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'buttons'                 => 'Dugmići',
    'icon'                    => 'Ikonica',
    'id'                      => 'ID',
    'create_date'             => 'Kreirano u',
    'update_date'             => 'Izmijenjeno u',
    'updated_at'              => 'Izmijenjeno u',
    'balance_before'          => 'Bilans prije',
    'balance_after'           => 'Bilans nakon',
    'name'                    => 'Ime',
    'role'                    => 'Uloga',
    'currentBalance'          => 'Trenutni bilans',
    'linked_to_rules'         => 'Relenvantna pravila',
    'active'                  => 'Aktivan?',
    'percentage'              => 'pct.',
    'recurring_transaction'   => 'Ponavljajuće transakcije',
    'next_due'                => 'Sledeći rok',
    'transaction_type'        => 'Tip',
    'lastActivity'            => 'Poslednja aktivnost',
    'balanceDiff'             => 'Razlika u bilansu',
    'other_meta_data'         => 'Ostali podaci',
    'invited_at'              => 'Pozvan u',
    'expires'                 => 'Pozivnica ističe',
    'invited_by'              => 'Pozvan od',
    'invite_link'             => 'Link poziva',
    'account_type'            => 'Tip računa',
    'created_at'              => 'Kreirano u',
    'account'                 => 'Račun',
    'external_url'            => 'Eksterni URL',
    'matchingAmount'          => 'Iznos',
    'destination'             => 'Destinacija',
    'source'                  => 'Izvor',
    'next_expected_match'     => 'Next expected match',
    'automatch'               => 'Auto match?',
    'drag_and_drop'           => 'Prevuci i pusti',
    'number'                  => 'Broj računa',
    'current_balance'         => 'Trenutni bilans',
    'last_activity'           => 'Poslednja aktivnost',
    'amount_due'              => 'Iznos duga',
    'balance_difference'      => 'Razlika u bilansu',
    'menu'                    => 'Meni',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'repeat_freq'             => 'Ponavlja se',
    'description'             => 'Opis',
    'amount'                  => 'Iznos',
    'date'                    => 'Datum',
    'interest_date'           => 'Datum kamate',
    'book_date'               => 'Datum transakcije',
    'process_date'            => 'Datum procesuiranja',
    'due_date'                => 'Krajnji rok',
    'payment_date'            => 'Datum plaćanja',
    'invoice_date'            => 'Datum fakture',
    'internal_reference'      => 'Internal reference',
    'notes'                   => 'Notes',
    'from'                    => 'From',
    'piggy_bank'              => 'Piggy bank',
    'to'                      => 'To',
    'budget'                  => 'Budget',
    'category'                => 'Category',
    'bill'                    => 'Bill',
    'withdrawal'              => 'Withdrawal',
    'deposit'                 => 'Deposit',
    'transfer'                => 'Transfer',
    'type'                    => 'Type',
    'completed'               => 'Completed',
    'iban'                    => 'IBAN',
    'account_number'          => 'Account number',
    'paid_current_period'     => 'Paid this period',
    'email'                   => 'Email',
    'registered_at'           => 'Registered at',
    'is_blocked'              => 'Is blocked',
    'is_admin'                => 'Is admin',
    'has_two_factor'          => 'Has 2FA',
    'blocked_code'            => 'Block code',
    'source_account'          => 'Source account',
    'destination_account'     => 'Destination account',
    'accounts_count'          => 'Number of accounts',
    'journals_count'          => 'Number of transactions',
    'attachments_count'       => 'Number of attachments',
    'bills_count'             => 'Number of bills',
    'categories_count'        => 'Number of categories',
    'budget_count'            => 'Number of budgets',
    'rule_and_groups_count'   => 'Number of rules and rule groups',
    'tags_count'              => 'Number of tags',
    'tags'                    => 'Tags',
    'inward'                  => 'Inward description',
    'outward'                 => 'Outward description',
    'number_of_transactions'  => 'Number of transactions',
    'total_amount'            => 'Total amount',
    'sum'                     => 'Sum',
    'sum_excluding_transfers' => 'Sum (excluding transfers)',
    'sum_withdrawals'         => 'Sum of withdrawals',
    'sum_deposits'            => 'Sum of deposits',
    'sum_transfers'           => 'Sum of transfers',
    'sum_reconciliations'     => 'Sum of reconciliations',
    'reconcile'               => 'Reconcile',
    'sepa_ct_id'              => 'SEPA End to End Identifier',
    'sepa_ct_op'              => 'SEPA Opposing Account Identifier',
    'sepa_db'                 => 'SEPA Mandate Identifier',
    'sepa_country'            => 'SEPA Country',
    'sepa_cc'                 => 'SEPA Clearing Code',
    'sepa_ep'                 => 'SEPA External Purpose',
    'sepa_ci'                 => 'SEPA Creditor Identifier',
    'sepa_batch_id'           => 'SEPA Batch ID',
    'external_id'             => 'External ID',
    'account_at_bunq'         => 'Account with bunq',
    'file_name'               => 'File name',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'file_size'               => 'File size',
    'file_type'               => 'File type',
    'attached_to'             => 'Attached to',
    'file_exists'             => 'File exists',
    'spectre_bank'            => 'Bank',
    'spectre_last_use'        => 'Last login',
    'spectre_status'          => 'Status',
    'bunq_payment_id'         => 'bunq payment ID',
    'repetitions'             => 'Repetitions',
    'title'                   => 'Title',
    'transaction_s'           => 'Transaction(s)',
    'field'                   => 'Field',
    'value'                   => 'Value',
    'interest'                => 'Interest',
    'interest_period'         => 'Interest period',
    'liability_type'          => 'Type of liability',
    'liability_direction'     => 'Liability in/out',
    'end_date'                => 'End date',
    'payment_info'            => 'Payment information',
    'expected_info'           => 'Next expected transaction',
    'start_date'              => 'Start date',
    'trigger'                 => 'Trigger',
    'response'                => 'Response',
    'delivery'                => 'Delivery',
    'url'                     => 'URL',
    'secret'                  => 'Secret',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
