<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'home'                   => 'Avaleht',
    'budgets'                => 'Budgets',
    'subscriptions'          => 'Tellimused',
    'transactions'           => 'Tehingud',
    'title_expenses'         => 'Kulutused',
    'title_withdrawal'       => 'Kulutused',
    'title_revenue'          => 'Revenue / income',
    'title_deposit'          => 'Revenue / income',
    'title_transfer'         => 'Ülekanded',
    'title_transfers'        => 'Ülekanded',
    'edit_currency'          => 'Muuda valuutat ":name"',
    'delete_currency'        => 'Kustuta valuuta ":name"',
    'newPiggyBank'           => 'Loo uus hoiupõrsas',
    'edit_piggyBank'         => 'Muuda hoiupõrsast ":name"',
    'preferences'            => 'Eelistused',
    'profile'                => 'Profiil',
    'accounts'               => 'Kontod',
    'changePassword'         => 'Muuda oma salasõna',
    'change_email'           => 'Muuda oma e-posti aadressi',
    'bills'                  => 'Arved',
    'newBill'                => 'Uus arve',
    'edit_bill'              => 'Muuda arvet ":name"',
    'delete_bill'            => 'Kustuta arve ":name"',
    'reports'                => 'Aruanded',
    'search_result'          => 'Otsingutulemus päringule ":query"',
    'withdrawal_list'        => 'Kulud',
    'Withdrawal_list'        => 'Kulud',
    'deposit_list'           => 'Tulu, sissetulek, sissemakse',
    'transfer_list'          => 'Ülekanded',
    'transfers_list'         => 'Ülekanded',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'reconciliation_list'    => 'Lepitused',
    'create_withdrawal'      => 'Loo uus väljakanne',
    'create_deposit'         => 'Loo uus sissekanne',
    'create_transfer'        => 'Loo uus ülekanne',
    'create_new_transaction' => 'Loo uus tehing',
    'edit_journal'           => 'Muuda tehingut ":description"',
    'edit_reconciliation'    => 'Muuda ":description"',
    'delete_journal'         => 'Kustuta tehing ":description"',
    'delete_group'           => 'Kustuta tehing ":description"',
    'tags'                   => 'Sildid',
    'createTag'              => 'Loo uus silt',
    'edit_tag'               => 'Muuda silti ":tag"',
    'delete_tag'             => 'Kustuta silt ":tag"',
    'delete_journal_link'    => 'Kustuta seos kahe tehingu vahel',
    'edit_object_group'      => 'Edit group ":title"',
    'delete_object_group'    => 'Delete group ":title"',
    'logout_others'          => 'Logout other sessions',
    'asset_accounts'         => 'Asset accounts',
    'expense_accounts'       => 'Expense accounts',
    'revenue_accounts'       => 'Revenue accounts',
    'liabilities_accounts'   => 'Kohustused',
    'placeholder'            => '[Placeholder]',

    // mfa
    'profile_mfa'            => 'Multi-factor authentication',
    'mfa_enableMFA'          => 'Enable multi-factor authentication',
    'mfa_backup_codes'       => 'Backup codes',
    'mfa_disableMFA'         => 'Disable multi-factor authentication',
];
