<?php

/**
 * form.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    // new user:
    'bank_name'                   => 'Panga nimi',
    'bank_balance'                => 'Balanss',
    'current_balance'             => 'Current balance',
    'savings_balance'             => 'Savings balance',
    'credit_card_limit'           => 'Krediitkaardi limiit',
    'automatch'                   => 'Match automatically',
    'skip'                        => 'Jäta vahele',
    'enabled'                     => 'Lubatud',
    'name'                        => 'Nimi',
    'active'                      => 'Aktiivne',
    'amount_min'                  => 'Minimaalne summa',
    'amount_max'                  => 'Maksimaalne summa',
    'match'                       => 'Matches on',
    'strict'                      => 'Strict mode',
    'repeat_freq'                 => 'Kordamised',
    'object_group'                => 'Group',
    'location'                    => 'Asukoht',
    'update_channel'              => 'Update channel',
    'currency_id'                 => 'Valuuta',
    'transaction_currency_id'     => 'Valuuta',
    'auto_budget_currency_id'     => 'Currency',
    'external_ip'                 => 'Serveri väline IP',
    'attachments'                 => 'Manused',
    'BIC'                         => 'BIC',
    'verify_password'             => 'Verify password security',
    'source_account'              => 'Source account',
    'destination_account'         => 'Saaja Konto',
    'asset_destination_account'   => 'Saaja Konto',
    'include_net_worth'           => 'Include in net worth',
    'asset_source_account'        => 'Source account',
    'journal_description'         => 'Kirjeldus',
    'note'                        => 'Märkused',
    'currency'                    => 'Valuuta',
    'account_id'                  => 'Vara konto',
    'budget_id'                   => 'Eelarve',
    'bill_id'                     => 'Bill',
    'opening_balance'             => 'Algsaldo',
    'tagMode'                     => 'Tag mode',
    'virtual_balance'             => 'Virtuaalne saldo',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'targetamount'                => 'Target amount',
    'account_role'                => 'Account role',
    'opening_balance_date'        => 'Algsaldo kuupäev',
    'cc_type'                     => 'Krediitkaardi tagasimakse plaan',
    'cc_monthly_payment_date'     => 'Krediitkaardi igakuuse makse kuupäev',
    'piggy_bank_id'               => 'Piggy bank',
    'returnHere'                  => 'Return here',
    'returnHereExplanation'       => 'After storing, return here to create another one.',
    'returnHereUpdateExplanation' => 'After updating, return here.',
    'description'                 => 'Description',
    'expense_account'             => 'Expense account',
    'revenue_account'             => 'Revenue account',
    'decimal_places'              => 'Decimal places',
    'destination_amount'          => 'Amount (destination)',
    'new_email_address'           => 'New email address',
    'verification'                => 'Verification',
    'api_key'                     => 'API key',
    'remember_me'                 => 'Remember me',
    'liability_type_id'           => 'Liability type',
    'liability_type'              => 'Liability type',
    'interest'                    => 'Interest',
    'interest_period'             => 'Interest period',
    'extension_date'              => 'Extension date',
    'type'                        => 'Type',
    'convert_Withdrawal'          => 'Convert withdrawal',
    'convert_Deposit'             => 'Convert deposit',
    'convert_Transfer'            => 'Convert transfer',
    'amount'                      => 'Amount',
    'foreign_amount'              => 'Foreign amount',
    'date'                        => 'Date',
    'interest_date'               => 'Interest date',
    'book_date'                   => 'Book date',
    'process_date'                => 'Processing date',
    'category'                    => 'Kategooria',
    'tags'                        => 'Sildid',
    'deletePermanently'           => 'Kustuta lõplikult',
    'cancel'                      => 'Tühista',
    'targetdate'                  => 'Target date',
    'startdate'                   => 'Alguskuupäev',
    'tag'                         => 'Silt',
    'under'                       => 'Under',
    'symbol'                      => 'Sümbol',
    'code'                        => 'Kood',
    'iban'                        => 'IBAN',
    'account_number'              => 'Konto number',
    'creditCardNumber'            => 'Krediitkaardi number',
    'has_headers'                 => 'Päised',
    'date_format'                 => 'Kuupäevaformaat',
    'specifix'                    => 'Bank- or file specific fixes',
    'attachments[]'               => 'Manused',
    'title'                       => 'Pealkiri',
    'notes'                       => 'Märkused',
    'filename'                    => 'Faili nimi',
    'mime'                        => 'Mime type',
    'size'                        => 'Maht',
    'trigger'                     => 'Päästik',
    'stop_processing'             => 'Stop processing',
    'start_date'                  => 'Start of range',
    'end_date'                    => 'End of range',
    'enddate'                     => 'End date',
    'move_rules_before_delete'    => 'Rule group',
    'start'                       => 'Start of range',
    'end'                         => 'End of range',
    'delete_account'              => 'Kustuta konto ":name"',
    'delete_webhook'              => 'Delete webhook ":title"',
    'delete_bill'                 => 'Kustuta arve ":name"',
    'delete_budget'               => 'Kustuta eelarve ":name"',
    'delete_category'             => 'Kustuta kategooria ":name"',
    'delete_currency'             => 'Kustuta valuuta ":name"',
    'delete_journal'              => 'Delete transaction with description ":description"',
    'delete_attachment'           => 'Kustuta manus ":name"',
    'delete_rule'                 => 'Kustuta reegel ":title"',
    'delete_rule_group'           => 'Kustuta reeglite grupp ":title"',
    'delete_link_type'            => 'Kustuta lingi tüüp ":name"',
    'delete_user'                 => 'Kustuta kasutaja ":email"',
    'delete_recurring'            => 'Delete recurring transaction ":title"',
    'user_areYouSure'             => 'If you delete user ":email", everything will be gone. There is no undo, undelete or anything. If you delete yourself, you will lose access to this instance of Firefly III.',
    'attachment_areYouSure'       => 'Are you sure you want to delete the attachment named ":name"?',
    'account_areYouSure'          => 'Are you sure you want to delete the account named ":name"?',
    'account_areYouSure_js'       => 'Are you sure you want to delete the account named "{name}"?',
    'bill_areYouSure'             => 'Are you sure you want to delete the bill named ":name"?',
    'rule_areYouSure'             => 'Are you sure you want to delete the rule titled ":title"?',
    'object_group_areYouSure'     => 'Are you sure you want to delete the group titled ":title"?',
    'ruleGroup_areYouSure'        => 'Are you sure you want to delete the rule group titled ":title"?',
    'budget_areYouSure'           => 'Are you sure you want to delete the budget named ":name"?',
    'webhook_areYouSure'          => 'Are you sure you want to delete the webhook named ":title"?',
    'category_areYouSure'         => 'Are you sure you want to delete the category named ":name"?',
    'recurring_areYouSure'        => 'Are you sure you want to delete the recurring transaction titled ":title"?',
    'currency_areYouSure'         => 'Are you sure you want to delete the currency named ":name"?',
    'piggyBank_areYouSure'        => 'Are you sure you want to delete the piggy bank named ":name"?',
    'journal_areYouSure'          => 'Are you sure you want to delete the transaction described ":description"?',
    'mass_journal_are_you_sure'   => 'Are you sure you want to delete these transactions?',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'tag_areYouSure'              => 'Are you sure you want to delete the tag ":tag"?',
    'journal_link_areYouSure'     => 'Are you sure you want to delete the link between <a href=":source_link">:source</a> and <a href=":destination_link">:destination</a>?',
    'linkType_areYouSure'         => 'Are you sure you want to delete the link type ":name" (":inward" / ":outward")?',
    'permDeleteWarning'           => 'Deleting stuff from Firefly III is permanent and cannot be undone.',
    'mass_make_selection'         => 'You can still prevent items from being deleted by removing the checkbox.',
    'delete_all_permanently'      => 'Delete selected permanently',
    'update_all_journals'         => 'Update these transactions',
    'also_delete_transactions'    => 'The only transaction connected to this account will be deleted as well.|All :count transactions connected to this account will be deleted as well.',
    'also_delete_transactions_js' => 'No transactions|The only transaction connected to this account will be deleted as well.|All {count} transactions connected to this account will be deleted as well.',
    'also_delete_connections'     => 'The only transaction linked with this link type will lose this connection.|All :count transactions linked with this link type will lose their connection.',
    'also_delete_rules'           => 'The only rule connected to this rule group will be deleted as well.|All :count rules connected to this rule group will be deleted as well.',
    'also_delete_piggyBanks'      => 'The only piggy bank connected to this account will be deleted as well.|All :count piggy bank connected to this account will be deleted as well.',
    'also_delete_piggyBanks_js'   => 'No piggy banks|The only piggy bank connected to this account will be deleted as well.|All {count} piggy banks connected to this account will be deleted as well.',
    'not_delete_piggy_banks'      => 'The piggy bank connected to this group will not be deleted.|The :count piggy banks connected to this group will not be deleted.',
    'bill_keep_transactions'      => 'The only transaction connected to this bill will not be deleted.|All :count transactions connected to this bill will be spared deletion.',
    'budget_keep_transactions'    => 'The only transaction connected to this budget will not be deleted.|All :count transactions connected to this budget will be spared deletion.',
    'category_keep_transactions'  => 'The only transaction connected to this category will not be deleted.|All :count transactions connected to this category will be spared deletion.',
    'recurring_keep_transactions' => 'The only transaction created by this recurring transaction will not be deleted.|All :count transactions created by this recurring transaction will be spared deletion.',
    'tag_keep_transactions'       => 'The only transaction connected to this tag will not be deleted.|All :count transactions connected to this tag will be spared deletion.',
    'check_for_updates'           => 'Check for updates',
    'liability_direction'         => 'Liability in/out',
    'delete_object_group'         => 'Delete group ":title"',
    'email'                       => 'Email address',
    'password'                    => 'Salasõna',
    'password_confirmation'       => 'Salasõna (uuesti)',
    'blocked'                     => 'Blokeeritud?',
    'blocked_code'                => 'Reason for block',
    'login_name'                  => 'Logi sisse',
    'is_owner'                    => 'Is admin?',
    'url'                         => 'URL',
    'bill_end_date'               => 'End date',

    // import
    'apply_rules'                 => 'Rakenda reeglid',
    'artist'                      => 'Esitaja',
    'album'                       => 'Album',
    'song'                        => 'Lugu',

    // admin
    'domain'                      => 'Domeen',
    'single_user_mode'            => 'Keela kasutajate registreerimine',
    'is_demo_site'                => 'On Demo leht',

    // import
    'configuration_file'          => 'Seadete fail',
    'csv_comma'                   => 'Koma (,)',
    'csv_semicolon'               => 'Semikoolon (;)',
    'csv_tab'                     => 'Tabulaator (invisible)',
    'csv_delimiter'               => 'CSV väljade eraldaja',
    'client_id'                   => 'Kliendi ID',
    'app_id'                      => 'Rakenduse ID',
    'secret'                      => 'Secret',
    'public_key'                  => 'Avalik võti',
    'country_code'                => 'Riigi kood',
    'provider_code'               => 'Bank or data-provider',
    'fints_url'                   => 'FinTS API URL',
    'fints_port'                  => 'Port',
    'fints_bank_code'             => 'Panga kood',
    'fints_username'              => 'Kasutajanimi',
    'fints_password'              => 'PIN / Password',
    'fints_account'               => 'FinTS account',
    'local_account'               => 'Firefly III account',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


    'from_date'                   => 'Alates kuupäevast',
    'to_date'                     => 'Kuni kuupäevani',
    'due_date'                    => 'Tähtaeg',
    'payment_date'                => 'Makse kuupäev',
    'invoice_date'                => 'Arve kuupäev',
    'internal_reference'          => 'Internal reference',
    'inward'                      => 'Inward description',
    'outward'                     => 'Outward description',
    'rule_group_id'               => 'Rule group',
    'transaction_description'     => 'Transaction description',
    'first_date'                  => 'First date',
    'transaction_type'            => 'Transaction type',
    'repeat_until'                => 'Korda kuni',
    'recurring_description'       => 'Recurring transaction description',
    'repetition_type'             => 'Type of repetition',
    'foreign_currency_id'         => 'Foreign currency',
    'repetition_end'              => 'Repetition ends',
    'repetitions'                 => 'Repetitions',
    'calendar'                    => 'Calendar',
    'weekend'                     => 'Weekend',
    'client_secret'               => 'Client secret',
    'withdrawal_destination_id'   => 'Destination account',
    'deposit_source_id'           => 'Source account',
    'expected_on'                 => 'Expected on',
    'paid'                        => 'Paid',
    'auto_budget_type'            => 'Auto-budget',
    'auto_budget_amount'          => 'Auto-budget amount',
    'auto_budget_period'          => 'Auto-budget period',
    'collected'                   => 'Collected',
    'submitted'                   => 'Submitted',
    'key'                         => 'Key',
    'value'                       => 'Content of record',
    'webhook_delivery'            => 'Delivery',
    'webhook_response'            => 'Response',
    'webhook_trigger'             => 'Trigger',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
