<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'buttons'                 => 'Nupud',
    'icon'                    => 'Ikoon',
    'id'                      => 'ID',
    'create_date'             => 'Loodud',
    'update_date'             => 'Uuendatud',
    'updated_at'              => 'Uuendatud',
    'balance_before'          => 'Saldo enne',
    'balance_after'           => 'Saldo pärast',
    'name'                    => 'Nimi',
    'role'                    => 'Roll',
    'currentBalance'          => 'Jooksevsaldo',
    'linked_to_rules'         => 'Relevant rules',
    'active'                  => 'Aktiivne?',
    'percentage'              => 'pct.',
    'recurring_transaction'   => 'Recurring transaction',
    'next_due'                => 'Next due',
    'transaction_type'        => 'Liik',
    'lastActivity'            => 'Viimane tegevus',
    'balanceDiff'             => 'Balance difference',
    'other_meta_data'         => 'Other meta data',
    'invited_at'              => 'Invited at',
    'expires'                 => 'Invitation expires',
    'invited_by'              => 'Invited by',
    'invite_link'             => 'Invite link',
    'account_type'            => 'Account type',
    'created_at'              => 'Created at',
    'account'                 => 'Account',
    'external_url'            => 'External URL',
    'matchingAmount'          => 'Amount',
    'destination'             => 'Destination',
    'source'                  => 'Source',
    'next_expected_match'     => 'Next expected match',
    'automatch'               => 'Auto match?',
    'drag_and_drop'           => 'Drag and drop',
    'number'                  => 'Account number',
    'current_balance'         => 'Current balance',
    'last_activity'           => 'Last activity',
    'amount_due'              => 'Amount due',
    'balance_difference'      => 'Balance difference',
    'menu'                    => 'Menu',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'repeat_freq'             => 'Repeats',
    'description'             => 'Description',
    'amount'                  => 'Amount',
    'date'                    => 'Date',
    'interest_date'           => 'Interest date',
    'book_date'               => 'Book date',
    'process_date'            => 'Processing date',
    'due_date'                => 'Due date',
    'payment_date'            => 'Payment date',
    'invoice_date'            => 'Invoice date',
    'internal_reference'      => 'Internal reference',
    'notes'                   => 'Notes',
    'from'                    => 'From',
    'piggy_bank'              => 'Piggy bank',
    'to'                      => 'To',
    'budget'                  => 'Budget',
    'category'                => 'Category',
    'bill'                    => 'Bill',
    'withdrawal'              => 'Withdrawal',
    'deposit'                 => 'Deposit',
    'transfer'                => 'Ülekanne',
    'type'                    => 'Liik',
    'completed'               => 'Lõpetatud',
    'iban'                    => 'IBAN',
    'account_number'          => 'Account number',
    'paid_current_period'     => 'Paid this period',
    'email'                   => 'E-mail',
    'registered_at'           => 'Registreeritud',
    'is_blocked'              => 'Blokeeritud',
    'is_admin'                => 'Administraator',
    'has_two_factor'          => 'Has 2FA',
    'blocked_code'            => 'Block code',
    'source_account'          => 'Source account',
    'destination_account'     => 'Saaja Konto',
    'accounts_count'          => 'Number of accounts',
    'journals_count'          => 'Ülekannete arv',
    'attachments_count'       => 'Manuste arv',
    'bills_count'             => 'Arvete arv',
    'categories_count'        => 'Kategooriate arv',
    'budget_count'            => 'Eelarvete arv',
    'rule_and_groups_count'   => 'Reeglite ja reegli gruppide arv',
    'tags_count'              => 'Number of tags',
    'tags'                    => 'Tags',
    'inward'                  => 'Inward description',
    'outward'                 => 'Outward description',
    'number_of_transactions'  => 'Ülekannete arv',
    'total_amount'            => 'Summa kokku',
    'sum'                     => 'Summa',
    'sum_excluding_transfers' => 'Summa (välja arvatud ülekanded)',
    'sum_withdrawals'         => 'Sum of withdrawals',
    'sum_deposits'            => 'Sissemaksete summa',
    'sum_transfers'           => 'Ülekannete summa',
    'sum_reconciliations'     => 'Sum of reconciliations',
    'reconcile'               => 'Reconcile',
    'sepa_ct_id'              => 'SEPA End to End Identifier',
    'sepa_ct_op'              => 'SEPA Opposing Account Identifier',
    'sepa_db'                 => 'SEPA Mandate Identifier',
    'sepa_country'            => 'SEPA Country',
    'sepa_cc'                 => 'SEPA Clearing Code',
    'sepa_ep'                 => 'SEPA External Purpose',
    'sepa_ci'                 => 'SEPA Creditor Identifier',
    'sepa_batch_id'           => 'SEPA Batch ID',
    'external_id'             => 'External ID',
    'account_at_bunq'         => 'Account with bunq',
    'file_name'               => 'Faili nimi',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'file_size'               => 'Suurus',
    'file_type'               => 'Faili tüüp',
    'attached_to'             => 'Attached to',
    'file_exists'             => 'File exists',
    'spectre_bank'            => 'Bank',
    'spectre_last_use'        => 'Last login',
    'spectre_status'          => 'Status',
    'bunq_payment_id'         => 'bunq payment ID',
    'repetitions'             => 'Repetitions',
    'title'                   => 'Title',
    'transaction_s'           => 'Transaction(s)',
    'field'                   => 'Field',
    'value'                   => 'Value',
    'interest'                => 'Interest',
    'interest_period'         => 'Interest period',
    'liability_type'          => 'Type of liability',
    'liability_direction'     => 'Liability in/out',
    'end_date'                => 'End date',
    'payment_info'            => 'Payment information',
    'expected_info'           => 'Next expected transaction',
    'start_date'              => 'Start date',
    'trigger'                 => 'Trigger',
    'response'                => 'Response',
    'delivery'                => 'Delivery',
    'url'                     => 'URL',
    'secret'                  => 'Secret',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
