<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'home'                   => 'Heim',
    'budgets'                => 'Budgets',
    'subscriptions'          => 'Subscriptions',
    'transactions'           => 'Transactions',
    'title_expenses'         => 'Expenses',
    'title_withdrawal'       => 'Expenses',
    'title_revenue'          => 'Revenue / income',
    'title_deposit'          => 'Revenue / income',
    'title_transfer'         => 'Transfers',
    'title_transfers'        => 'Transfers',
    'edit_currency'          => 'Breyta gjaldmiðli ":name"',
    'delete_currency'        => 'Eyða gjaldmiðli ":name"',
    'newPiggyBank'           => 'Búa til nýjan sparigrís',
    'edit_piggyBank'         => 'Breyta sparigrís ":name"',
    'preferences'            => 'Stillingar',
    'profile'                => 'Prófíll',
    'accounts'               => 'Bankareikningar',
    'changePassword'         => 'Breyta lykilorði',
    'change_email'           => 'Breyta netfangi',
    'bills'                  => 'Reikningar',
    'newBill'                => 'Nýr reikningur',
    'edit_bill'              => 'Breyta reikningi ":name"',
    'delete_bill'            => 'Eyða reikningi ":name"',
    'reports'                => 'Skýrslur',
    'search_result'          => 'Leitarniðurstöður fyrir ":query"',
    'withdrawal_list'        => 'Útgjöld',
    'Withdrawal_list'        => 'Útgjöld',
    'deposit_list'           => 'Afrakstur, tekjur og innborganir',
    'transfer_list'          => 'Færslur',
    'transfers_list'         => 'Færslur',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'reconciliation_list'    => 'Afstemming',
    'create_withdrawal'      => 'Stofna nýja úttekt',
    'create_deposit'         => 'Sofna nýja innborgun',
    'create_transfer'        => 'Stofna nýja færslu',
    'create_new_transaction' => 'Stofna nýja færslu',
    'edit_journal'           => 'Breyta færslu ":description"',
    'edit_reconciliation'    => 'Breyta ":description"',
    'delete_journal'         => 'Eyða færslu ":description"',
    'delete_group'           => 'Eyða færslu ":description"',
    'tags'                   => 'Merki',
    'createTag'              => 'Stofna nýtt merki',
    'edit_tag'               => 'Breyta merki ":tag"',
    'delete_tag'             => 'Eyða merki ":tag"',
    'delete_journal_link'    => 'Eyða tengingu milli færslna',
    'edit_object_group'      => 'Breyta hópi ":title"',
    'delete_object_group'    => 'Eyða hópi ":title"',
    'logout_others'          => 'Skrá út úr öðrum setum',
    'asset_accounts'         => 'Asset accounts',
    'expense_accounts'       => 'Expense accounts',
    'revenue_accounts'       => 'Revenue accounts',
    'liabilities_accounts'   => 'Liabilities',
    'placeholder'            => '[Placeholder]',
];
