<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'no_demo_text'           => 'Því miður er enginn frekari prufu-útskýringartexti fyrir <abbr title=":route">þessa síðu</abbr>.',
    'see_help_icon'          => 'Hinsvegar gæti <i class="fa fa-question-circle"></i>-táknið í efra hægra horninu sagt þér meira.',
    'index'                  => 'Velkomin í <strong>Firefly III</strong>! Á þessari síðu færðu gróft fjármálayfirlit. Skoðaðu síðurnar fyrir Bankareikninga &rarr; <a href=":asset">Eignareikninga</a> og auðvitað <a href=":budgets">Fjárhagsáætlanir</a> og <a href=":reports">Skýrslur</a> fyrir frekari upplýsingar. Eða skoðaðu þig bara um og sjáðu hvar þú endar.',
    'accounts-index'         => 'Eignareikningar eru þínir persónulegu bankareikingar. Útgjaldareikningar er allt það sem þú eyðir peningi í, t.a.m. verslanir og vinir. Tekjureikningar er allt sem þú færð tekjur frá, t.d. vinnustaðurinn þinn, ríkið eða aðrar tekjulindir. Skuldir eru allar skuldir og lán eins og gamlar kreditkortaskuldir eða námslán. Þú getur breytt þeim eða eytt á þessari síðu.',
    'budgets-index'          => 'Þessi síða sýnir þér yfirlit af fjárhagsáætlunum þínum. Efri stikan sýnir þá fjárhæð sem má úthluta. Þetta má sérsníða fyrir hvaða tímabil sem er með því að smella á fjárhæðina hægra megin. Sú fjárhæð sem hefur verið eytt er sýnd á stikunni fyrir neðan. Fyrir neðan það eru annars vegar útgjöld og hins vegar úthlutað fjármagn fyrir hverja fjárhagsáætlun fyrir sig.',
    'reports-index-start'    => 'Firefly III styður margs konar skýrslur. Lestu um það með því að smella á <i class="fa fa-question-circle"></i>-táknið í efra hægra horninu.',
    'reports-index-examples' => 'Vertu vís að athuga eftirfarandi dæmi: <a href=":one">mánaðarlegt fjárhagsyfirlit</a>,<a href=":two">árlegt fjárhagsyfirlit</a> og <a href=":three">yfirlit fjárhagsáætlunar</a>.',
    'currencies-index'       => 'Firefly III styður marga gjaldmiðla. Þó að Evran sé sjálfgefna stillingin má breyta því í íslenska krónu og margar aðrar myntir. Eins og sjá má er lítið safn gjaldmiðla nú þegar sett upp en það má auðveldlega bæta við fleirum. Breyting á sjálfgefna gjaldmiðlinum breytir ekki gjaldmiðli þeirra gamalla færslna: Firefly III styður notkun margra gjaldmiðla í einu.',
    'transactions-index'     => 'Þessi útgjöld, innborganir og færslur eru ekki sérlega frumlegar. Þær hafa verið útbúnar sjálfkrafa.',
    'piggy-banks-index'      => 'Eins og sjá má eru til þrír sparigrísir. Plús og mínus takkarnir breyta fjárhæðinni í hverjum sparigrís. Smelltu á nafn sparigríss til að sjá stjórnun þess.',
    'profile-index'          => 'Hafðu í huga að þessi prufusíða endurræsist á nokkura klukkutíma fresti. Aðgangur þinn gæti verið afturkallaður hvenær sem er. Þetta gerist sjálfkrafa og er ekki galli.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
